title: Chao Wang's Homepage
page-top-title: Chao Wang
top-section-bg-text: Computer Science and Vehicle Routing Problem
home-subtitle: Chao Wang&ensp;|&ensp;姓名
copyright-text: '&copy; Chao Wang 2026. All Rights Reserved.'
